const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"公告类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryNews"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"任务类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryPaotuirenwu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"投诉类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryYonghutousu"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "状态",
                            "删除"
                        ],
                        "menu":"接单详情管理",
                        "menuJump":"列表",
                        "tableName":"jiedanxiangqing"
                    }
                ],
                "menu":"接单详情管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"接单员管理",
                        "menuJump":"列表",
                        "tableName":"jiedanyuan"
                    }
                ],
                "menu":"接单员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告信息管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"跑腿任务管理",
                        "menuJump":"列表",
                        "tableName":"paotuirenwu"
                    }
                ],
                "menu":"跑腿任务管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"收货地址管理",
                        "menuJump":"列表",
                        "tableName":"shouhuodizhi"
                    }
                ],
                "menu":"收货地址管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "审核",
                            "删除"
                        ],
                        "menu":"用户投诉管理",
                        "menuJump":"列表",
                        "tableName":"yonghutousu"
                    }
                ],
                "menu":"用户投诉管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"余额变更记录管理",
                        "menuJump":"列表",
                        "tableName":"yuebiangengjil"
                    }
                ],
                "menu":"余额变更记录管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                    ],
	                    "menu":"公告信息管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "删除"
	                    ],
	                    "menu":"跑腿任务管理",
	                    "menuJump":"列表",
	                    "tableName":"paotuirenwu"
	                }
	            ],
	            "menu":"跑腿任务管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			            ],
			            "menu":"接单详情管理",
			            "menuJump":"列表",
			            "tableName":"jiedanxiangqing"
			        }
			    ],
			    "menu":"接单详情管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"收货地址管理",
	                    "menuJump":"列表",
	                    "tableName":"shouhuodizhi"
	                }
	            ],
	            "menu":"收货地址管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "删除"
	                    ],
	                    "menu":"用户投诉管理",
	                    "menuJump":"列表",
	                    "tableName":"yonghutousu"
	                }
	            ],
	            "menu":"用户投诉管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"余额变更记录管理",
	                    "menuJump":"列表",
	                    "tableName":"yuebiangengjil"
	                }
	            ],
	            "menu":"余额变更记录管理"
	        }
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"用户",
	    "tableName":"yonghu"
	},
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                    ],
	                    "menu":"公告信息管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "接单",
	                    ],
	                    "menu":"跑腿任务管理",
	                    "menuJump":"列表",
	                    "tableName":"paotuirenwu"
	                }
	            ],
	            "menu":"跑腿任务管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "状态",
			            ],
			            "menu":"接单详情管理",
			            "menuJump":"列表",
			            "tableName":"jiedanxiangqing"
			        }
			    ],
			    "menu":"接单详情管理"
			}
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"接单员",
	    "tableName":"jiedanyuan"
	}
]
    }
}
export default menu;
